Repository RussStation/RussStation, pull requests merged in 2022-09, with the labels that each got.

#342 Fix Lima Atmos Scrubber Pipe
  _maps/map_files/LimaStation/Lima.dmm
Labels: bugfix, maaap

#340 Echo postmerge updates
  _maps/map_files/EchoStation/EchoStation.dmm
Labels: maaap

#334 fixes Diona being dumb
  russstation/code/modules/mob/living/carbon/human/species_types/diona.dm
Labels: Feature request

#339 Mothroach? Mothroach.
  RussStation.dme
  code/datums/ai/basic_mobs/basic_subtrees/speech_subtree.dm
  code/datums/components/crafting/recipes.dm
  code/game/objects/items/food/meat.dm
  code/game/objects/items/stacks/sheets/leather.dm
  code/modules/cargo/packs.dm
  code/modules/mob/living/basic/vermin/mothroach.dm
  icons/mob/animal.dmi
  icons/mob/animal_item_head.dmi
  icons/mob/animal_item_lh.dmi
  icons/mob/animal_item_rh.dmi
  icons/obj/stack_objects.dmi
Labels: Feature request

#327 Kitsune Race!
  RussStation.dme
  code/__DEFINES/DNA.dm
  code/__DEFINES/traits.dm
  code/__DEFINES/~russ_defines/DNA.dm
  code/__DEFINES/~russ_defines/is_helpers.dm
  code/__DEFINES/~russ_defines/mobs.dm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/mobs.dm
  code/_globalvars/phobias.dm
  code/_globalvars/traits.dm
  code/datums/components/tackle.dm
  code/datums/dna.dm
  code/game/machinery/limbgrower.dm
  code/game/machinery/scan_gate.dm
  code/modules/admin/create_mob.dm
  code/modules/language/language_holder.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/research/designs/limbgrower_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/surgery/organs/tongue.dm
  config/game_options.txt
  icons/ass/assfox.png
  russstation/code/__HELPERS/mobs.dm
  russstation/code/__HELPERS/names.dm
  russstation/code/_globalvars/lists/flavor_misc.dm
  russstation/code/_globalvars/lists/names.dm
  russstation/code/game/objects/items/food/meat.dm
  russstation/code/game/objects/items/stacks/sheets/leather.dm
  russstation/code/modules/client/preferences/species_features/kitsune.dm
  russstation/code/modules/language/kitsumimetic.dm
  russstation/code/modules/language/language_holder.dm
  russstation/code/modules/mob/dead/new_player/sprite_accessories.dm
  russstation/code/modules/mob/living/carbon/human/species_types/kitsune.dm
  russstation/code/modules/reagents/chemistry/reagents/other_reagents.dm
  russstation/code/modules/surgery/organs/ears.dm
  russstation/code/modules/surgery/organs/external/tails.dm
  russstation/icons/misc/language.dmi
  russstation/icons/mob/mutant_bodyparts.dmi
  russstation/icons/obj/clothing/hats.dmi
  russstation/icons/obj/stack_objects.dmi
  russstation/icons/obj/surgery.dmi
  russstation/strings/names/kitsune_first.txt
  russstation/strings/names/kitsune_last.txt
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/species_features.tsx
Labels: Feature request

#343 APC Cleanup
  _maps/map_files/CubeStation/Cube.dmm
  _maps/map_files/EchoStation/EchoStation.dmm
  _maps/map_files/IceCubeStation/IceCube.dmm
  _maps/map_files/LimaStation/Lima.dmm
Labels: maaap

#344 Xenobio Bag Fix + Ore Satchel & Reagent Grinder
  code/datums/storage/storage.dm
  code/modules/mining/satchel_ore_boxdm.dm
  code/modules/reagents/chemistry/machinery/reagentgrinder.dm
Labels: bugfix

#346 Kitsune Dexterity Unfuckery
  russstation/code/modules/mob/living/carbon/human/species_types/kitsune.dm
Labels: bugfix

#345 Multilingual quirk
  RussStation.dme
  russstation/code/_globalvars/lists/quirks.dm
  russstation/code/datums/quirks/good.dm
  russstation/code/modules/client/preferences/multilingual.dm
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/multilingual.tsx
Labels: Feature request

#350 Fixes rendering for byond 514.1587
  code/_onclick/hud/rendering/plane_master.dm
Labels: bugfix, Upstream

#349 Fixes multilingual only being applied to humans
  russstation/code/_globalvars/lists/quirks.dm
  russstation/code/datums/quirks/good.dm
Labels: bugfix

#347 IceCube brig entrance access fix + Cold alarm fixes
  _maps/map_files/IceCubeStation/IceCube.dmm
Labels: bugfix, maaap

#348 Roundstart Atmos Tile Difference Fix
  _maps/map_files/CubeStation/Cube.dmm
  _maps/map_files/EchoStation/EchoStation.dmm
  _maps/map_files/ShitStation/ShitStation.dmm
Labels: bugfix, maaap
