Repository RussStation/RussStation, pull requests merged in 2022-10, with the labels that each got.

#359 Lavaland specific dwarf species created | Prevents issues due to station dwarf changes
  code/__DEFINES/~russ_defines/is_helpers.dm
  code/__DEFINES/~russ_defines/mobs.dm
  code/game/turfs/closed/minerals.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/hivelord.dm
  code/modules/unit_tests/screenshot_humanoids.dm
  code/modules/unit_tests/species_whitelists.dm
  russstation/code/game/objects/items/blueprints.dm
  russstation/code/game/objects/items/granters/crafting/dwarf_craft.dm
  russstation/code/modules/language/language_holder.dm
  russstation/code/modules/mob/living/carbon/human/species_types/dwarf.dm
  russstation/code/modules/mob_spawn/ghost_roles/mining_roles.dm
Labels: bugfix

#355 Sugma Station: New Funky Mode
  RussStation.dme
  _maps/map_files/Mining/Badlands.dmm
  _maps/map_files/ShitStation/ShitStation.dmm
  _maps/shitstation.json
  _maps/shuttles/arrival_shit.dmm
  _maps/shuttles/emergency_shit.dmm
  code/__DEFINES/~russ_defines/maps.dm
  code/controllers/subsystem/mapping.dm
  russstation/code/controllers/subsystem/ticker.dm
  russstation/code/datums/mapgen/Cavegens/Badlands.dm
  russstation/code/datums/ruins/badlands.dm
  russstation/code/datums/station_traits/negative_traits.dm
  russstation/code/game/area/areas/mining.dm
  russstation/code/game/turfs/closed/minerals.dm
  russstation/code/modules/antagonists/nukeop/equipment/pinpointer.dm
  russstation/code/modules/mining/badlands.dm
  russstation/code/modules/power/apc.dm
  russstation/code/modules/vending/monkey.dm
  russstation/icons/obj/decals.dmi
Labels: maaap

#354 Lima cube 9/23/22 update
  _maps/map_files/CubeStation/Cube.dmm
  _maps/map_files/EchoStation/EchoStation.dmm
  _maps/map_files/LimaStation/Lima.dmm
Labels: maaap

#351 Adds queekish language to borgs
  code/modules/language/language_holder.dm
Labels: Feature, Balance

#358 Update TGS DMAPI
  code/__DEFINES/tgs.dm
  code/modules/tgs/README.md
  code/modules/tgs/v3210/api.dm
  code/modules/tgs/v5/api.dm
Labels: Upstream

#353 Chasm Fishing (by Jacquere)
  RussStation.dme
  code/__DEFINES/fishing.dm
  code/datums/components/chasm.dm
  code/datums/elements/diggable.dm
  code/game/turfs/open/asteroid.dm
  code/game/turfs/open/floor/fancy_floor.dm
  code/modules/fishing/fish/chasm_detritus.dm
  code/modules/fishing/fish/fish_types.dm
  code/modules/fishing/fishing_equipment.dm
  code/modules/fishing/fishing_rod.dm
  code/modules/fishing/sources/_fish_source.dm
  code/modules/fishing/sources/source_types.dm
  icons/obj/aquarium.dmi
  icons/obj/fishing.dmi
Labels: Feature, Upstream
